### ISSUE TITLE
Org profile picture

### ISSUE THREAD

**Issue by jsharpe** [bazel-contrib/SIG-rules-authors#4]
I'm guessing we can't just reuse the bazelbuild logo so we'll need some one to design something to have as our org profile picture.

**Comment by alexeagle** [comment]
@pcj has the wireframe version of the Bazel logo he has used for some of his products, maybe we could adopt that?

**Comment by aaliddell** [comment]
Since you'll want some sort of 'identity' for #28 docs pages, I doodled some letters from the org initials:

![image](https://user-images.githubusercontent.com/9061354/150881426-03ad6caf-623d-49e8-9725-f4967de14303.png)

Or you could go wtih an odd abstract hybrid for something more compact:

![image](https://user-images.githubusercontent.com/9061354/150881821-07666627-55ea-4b4c-b559-60607607a090.png)

Take it if you want it. I won't be offended if you don't. Colour scheme is flexible. Needs tidying. I'm sure the folded style has come from somewhere but I can't think where.

**Comment by alexeagle** [comment]
Works for me as a placeholder, I think it's better than the GitHub-generated one anyhow.

**Comment by aaliddell** [comment]
Here's the files with a proper export rather than a screen grab. Also I fixed the broken gradient on the left of the compact one

[logo-inkscape.zip](https://github.com/bazel-contrib/SIG-rules-authors/files/7934581/logo-inkscape.zip)

**Comment by alexeagle** [comment]
Thanks, the transparency looks better too.
