### ISSUE TITLE
Our rules template should be discoverable

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#44]
Where would a user typically look before starting a new Bazel ruleset? https://bazel.build/rules/rules-tutorial seems like a good example.

These should link to our https://github.com/bazel-contrib/rules-template so that more developers discover and use it, rather than reinvent things that work less well.

**Comment by jdob** [comment]
I'll take care of getting this added to the tutorial page on the site.

**Comment by jdob** [comment]
The tutorial has been updated to include a call out to the template.

Additionally, we are currently having some discussions about reworking some of the navigation on the site. I'll keep this link in mind to include there as well, since we are looking to have a smoother on ramp for new devs. In other words, I'd like to see this mentioned in the docs themselves rather than just a tutorial.

**Comment by alexeagle** [comment]
Thanks!
