### ISSUE TITLE
Publish a gitstats for Bazel rules

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/SIG-rules-authors#59]
Possibly a component of #2 - @gregmagolan created https://gregmagolan.github.io/bazel_git_stats/ which is just the gitstats tool run over the bazelbuild org. It has useful data about the code and the contributors, but nothing is keeping it up-to-date.

**Comment by realtimetodie** [comment]
**Pitch: Use a GitHub Bot to collect data**

A **GitHub Bot** to collect release information and activity metrics using [Probot](https://github.com/probot/probot), a framework for building [GitHub Apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps).

![20230118_18h21m25s_grim](https://user-images.githubusercontent.com/72995223/213256112-4681f453-4de2-4c9c-96bb-5642252af650.png)

Users can install the GitHub Bot from [GitHub Marketplace](https://github.com/marketplace?type=) into their repository or organization.

GitHub Apps can listen to [GitHub webhook events](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/about-webhooks) sent by a repository

- [GitHub release event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release)

    Example

    ```javascript
    module.exports = (app) => {
      app.on("release", async (context) => {
        // A Bazel rules release was made in the repo, what should we do with it?
        app.log.info(context);
      });
    };
    ```

- [GitHub commit event](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#commit)

    Example

    ```javascript
    module.exports = (app) => {
      app.on("push", async (context) => {
        // Code was pushed to a Bazel rules repository, what should we do with it?
        app.log.info(context);
      });
    };
    ```

As a data endpoint, a [Cloud Function](https://cloud.google.com/functions) could be used, that would take an incoming HTTP request and store the data in [Firestore](https://firebase.google.com/docs/firestore).

To prevent abuse and spam, a repository approval process could be established to verify new installations first, before collecting data.

The GitHub Bot should be seen as the primary building block to collect data using  [GitHub webhook events](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/about-webhooks) instead of polling the GitHub API from a script.

**Comment by alexeagle** [comment]
Yes @kormide has written approximately that same thing already in https://github.com/bazel-contrib/publish-to-bcr
